#!/bin/bash
set -e

PORT=4000

while [[ $# -gt 0 ]]; do
    case $1 in
        --port)
            PORT="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

cd "$(dirname "$0")/docs"
eval "$(rbenv init -)"
bundle exec jekyll serve --livereload --port "$PORT"
